mode: auto

avatar:
  url: https://cdn.jsdelivr.net/gh/Thanafox/fox_blog/source/images/avatar.jpg
  status:
    enable: true
    emoji: ğŸ¦Š
    message: Looking for dawn.

github_issues:
  enable: true
  username: Thanafox
  repository: fox_blog
  filters: is:issue

github_discussions:
  enable: true
  username: Thanafox
  repository: Thanafox/fox_blog

bg_image:
  enable: true
  url: https://cdn.jsdelivr.net/gh/Thanafox/fox_blog/source/images/wfox.jpg
  dark: https://cdn.jsdelivr.net/gh/Thanafox/fox_blog/source/images/fffox.jpg

footer:
  since: 2024
  custom_text:

engine_search:
  enable: false

google_analytics:
  enable: true
  id: G-1LL0D86CY9

google_adsense:
  enable: true
  client: ca-pub-2245427233262012

post_edit:
  enable: true
  url: https://github.com/YunYouJun/yunyoujun.github.io/tree/hexo/source/

albums:
  enable: true

girls:
  enable: true

waline:
  enable: true
  serverURL: https://gleaming-madeleine-bcf0fa.netlify.app
  visitor: true
  comment: true
  version: 3.2.2

comment:
  enable: true
  tips:
  candidates:
    - waline

utterances:
  enable: false
  repo: Thanafox/fox_blog
  issue-term: pathname
  # label: comment
  theme: github-light

tags:
  åŠ¨ç”»: crimson
  æ¼«ç”»: orange
  Parcel: '#21374b'
  å­¦ä¹ : saddlebrown
  MAD: crimson
  æ•™ç¨‹: royalblue
  ç¬”è®°: dimgray
  åˆ†äº«: '#0078e7'
  éšç¬”: mediumpurple
  Blender: '#d04d2d'
  Linux: '#2577b1'
  ä¸­ä¼ : '#ccb44b'
  éƒ¨è½: '#DD306A'
  ç§‘å¹»: midnightblue
  èš‚èšæ£®æ—: '#54a892'

categories:
  äº‘æ¸¸çš„å°è§†é¢‘: '#FB7299'

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: ri:women-line
    color: hotpink

menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: ri:clipboard-line

cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: true
  id: GTM-M9KWR9L

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false


banner:
  enable: true
  title: é£ç‹ä¹‹ä¸‹
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

social:
  - name: GitHub
    link: https://github.com/Thanafox
    icon: ri:github-line
    color: '#6e5494'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/186574162
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: E-Mail
    link: mailto:15311490955@163.com
    icon: ri:mail-line
    color: '#8E71C1'

color:
  - bg: "#f08848"

# pjax:
#   enable: true